---
language: python
python: "2.7"

# Use the new container infrastructure
sudo: required

# Install ansible
addons:
  apt:
    packages:
    - python-pip

install:
  # Install ansible
  - pip install ansible

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  # Syntax check
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check

  # First run check
  - ansible-playbook tests/test.yml -i tests/inventory --connection=local --sudo

  # Idempotency test
  - >
    ansible-playbook tests/test.yml -i tests/inventory --connection=local --sudo
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)

  # Test correctness
  - stat /home/openbazaar/openbazaar/ob.cfg
  - stat /etc/init/openbazaard.conf
  - initctl status openbazaard

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
